# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
sections = [{:course => 'CSCE 482', :section => '599'},
            {:course => 'CSCE 482', :section => '598'}]

projects = [{:title => 'Citation Suggestion Tool', :description => 'When writing or presenting academic work, it is critical to be aware of and reference relevant related work. It can be challenging to identify such work or check that work is not missing. Develop an application that leverages online citation relationship data (e.g., CiteSeerX, Google Scholar, ResearchGate, etc) to suggest additional related work for an input citation list. For example, if another cites many of the same references in the input list, it is likely highly related. If a paper is often cited by references in the input list, it may also be worth noting. The application should support input of citations via .bib files used by BibTeX/LaTeX.', :max_group_size => 4, :min_group_size => 2, :topics => '', :hardware => false, :industry_sponsored => false, :client => nil},
            {:title => 'Savvy Textbook Shopper', :description => 'Develop an application to collect data from local and online textbook retailers to find the cheapest way to purchase all textbooks for an input class schedule. Users should be able to customize search based on preferences such as format type, condition, required only/all recommended, memberships for discount shipping rates, retailers to include/exclude, etc.', :max_group_size => 4, :min_group_size => 2, :topics => '', :hardware => false, :industry_sponsored => false, :client => nil},
            {:title => 'Power Grid Protection Visual Logic Analyzer', :description => 'The reliability of the electrical power grid is increasingly dependent on embedded microprocessors devices called relays that dynamically change the grid’s topology of power lines based on a variety of sensor input. Much of this activity is controlled by complex, customizable Boolean logic networks which combine sensor data in a manner defined by the power system design engineer (on case by case basis). Design an application that reads a Boolean logic specification, creates a visual display of the network of logic gates, and allows engineers to dynamically step through the logic evaluation, based on a time series of sensor data. The interface should allow input of expected output values (based on engineer’s understanding of configuration), so that variances between this and actual operation are quickly understood.', :max_group_size => 5, :min_group_size => 3, :topics => '', :hardware => , :industry_sponsored => true, :client => 'SynchroGrid'},
            {:title => 'Power Grid Visualizer for Localized Fault Analysis Studies', :description => 'The reliability of the electrical power grid is increasingly dependent on embedded microprocessors devices called relays that dynamically change the grid’s topology of power lines based on a variety of sensor input. The configuration of these relays is highly dependent on the “neighborhood” topology surrounding it, which is modeled as graph of substations (vertices) and transmission lines (edges). Simulations of electrical faults in the neighborhood play a pivotal role in this activity and must be considered by the power system design engineer. Design a visualizer for local areas of a power grid, based on inspection of the graph data structure and provide an intuitive overview of the system at an appropriate level of detail for the design workflow. Overlay big data visualizations derived from fault studies, either from provided data files or by dynamically running the simulations during interface interaction by the engineer.', :max_group_size => 5, :min_group_size => 3, :topics => '', :hardware => , :industry_sponsored => true, :client => 'SynchroGrid'},
            {:title => 'Crowdsourced Floodwater Depth Mapping', :description => 'Design and implement a mobile application that allows users to upload a flood photo (of a neighborhood, road, or intersection) and uses the photo\'s meta-data (camera coordinates, direction of look, time, etc.) to find the corresponding location on Google Street View. The photos may be existing photos or newly taken photos. The app will display the two images side-by-side (the street view image and user-uploaded flood photo) for the user to visually compare them to see the extent of flood damage in that particular location. The app will then pair these two images and upload them to the cloud for further analysis by a professional team. The app will also display a map noting where photos have been pinned for the user to view.', :max_group_size => 4, :min_group_size => 2, :topics => '', :hardware => false, :industry_sponsored => true, :client => 'Department of Construction Science'},
            {:title => 'Correcting Cam', :description => 'Develop a computer vision tracking method to quickly and accurately determine the relative motion (magnitude and direction) of a user\'s face to the camera itself. The tracking camera will be placed such that only a region of the face (rather than the full face) is in the field of view (FOV). When activated, the tracker method will receive image frames from the system and should enter a phase where it identifies and captures key features in the FOV and \'locks\' on to those as reference features. It will then track those features and return the magnitude and direction of motion to the caller. This tracker method will be deployed in a low power, embedded system. Expected operating parameters include <2GB RAM, ~1-1.5Ghtz quad core processors, and GPU should be optional. The image frames will be low resolution (QVGA or less) and any classification methods (machine learning or traditional cascades) are options if they can operate completely on-board the system. Critical factors for success are speed and accuracy and system resource costs as measured by power consumption.', :max_group_size => 5, :min_group_size => 3, :topics => '', :hardware => , :industry_sponsored => true, :client => 'Krueger Labs'},
            {:title => 'Athlete Sensor Data Tracking', :description => 'Develop a mobile application can pair and communicate with an embedded device (that provides sensor data including accelerometer, gyroscope, and bio markers), provide user notifications, and display the data in a graphical interface. The app will pair with an embedded Linux system; most likely via Bluetooth. The embedded device will transmit data to the device and the device should receive this data and then use it to provide alerts to the phone user, store historical data, and display the data sets. Success factors include a clean user interface with the ability to connect to a device via Bluetooth and the ability to push notifications.', :max_group_size => 5, :min_group_size => 3, :topics => '', :hardware => true, :industry_sponsored => true, :client => 'Krueger Labs'},
            {:title => 'Medical Sensor Data Analyzer', :description => 'Develop a method to quickly and accurately analyze the correlation of sensor data and bio markers to detect trauma events requiring professional evaluation. Data from the embedded device will be analyzed for three specific conditions and compared against a provided standard. It must accurately determine whether one or more of the three conditions are present notify personnel. The project will need to operate in a low power, embedded, environment. Key success factors include accuracy, minimizing system resources, and speed.', :max_group_size => 5, :min_group_size => 3, :topics => '', :hardware => true, :industry_sponsored => true, :client => 'Krueger Labs'},
            {:title => 'Sensor Fusion', :description => 'Develop a method to efficiently merge readings from a set of sensors (a magnetometer, accelerometer, and gyroscope) to reduce uncertainty in head motion data. The project will be part of an embedded system that requires low power and battery consumption while delivering accurate positional data at a preferred rate of over 250 Hertz. It is desired for the overall performance to exceed what can be done using a basic Kalman filter. The project will also develop a visual interface for the input and output data. The primary performance categories are speed, accuracy, and minimizing system resource utilization.', :max_group_size => 5, :min_group_size => 3, :topics => '', :hardware => true, :industry_sponsored => true, :client => 'Krueger Labs'},
            {:title => 'Agricultural Helper', :description => 'Develop a system to assist growers by alerting if plants need water, if plantings require weeding, if diseases and bug infestations appear, etc. The system should also scare away any animals attempting to access produce. The system should operate in all light levels and withstand typical outdoor temperatures.', :max_group_size => 5, :min_group_size => 3, :topics => '', :hardware => true, :industry_sponsored => false, :client => nil},
            {:title => 'Musician Tutor', :description => 'Many students learning to play an instrument need visual training until they can “play by ear”. Develop an application that can detect strumming patterns in a played piece of music and display the timing and strum direction visually. It should support live and recorded music, and interface with popular online music services (ex: YouTube, Spotify, Google Play, Apply Music).', :max_group_size => 5, :min_group_size => 3, :topics => '', :hardware => true, :industry_sponsored => false, :client => nil},
            {:title => 'Do Not Disturb Doorbell', :description => 'Develop a smart doorbell that does not ring during certain times of day if it detects delivery personnel or solicitors but instead sends an alert via txt/email.', :max_group_size => 5, :min_group_size => 3, :topics => '', :hardware => true, :industry_sponsored => false, :client => nil}]

# students = [{:first_name => 'Ethan', :last_name => 'Partin', :gender => 'M', :ethnicity => 'Hispanic or Latino', :topics => 'Algorithms,Artificial Intelligence,Compiler Theory', :hardware => false, :electives => 'CSCE 411,CSCE 470', :preferences => }]
